## Generalized Least Squares with Statsmodels

In [1]:
import statsmodels.api as sm

In [25]:
# Import longley dataset (timeseries)
data = sm.datasets.longley.load()
data.exog = sm.add_constant(data.exog)

In [29]:
data.endog = data.endog.to_numpy()
data.endog

array([60323., 61122., 60171., 61187., 63221., 63639., 64989., 63761.,
       66019., 67857., 68169., 66513., 68655., 69564., 69331., 70551.])

In [32]:
data.exog = data.exog.to_numpy()
data.exog

array([[1.00000e+00, 8.30000e+01, 2.34289e+05, 2.35600e+03, 1.59000e+03,
        1.07608e+05, 1.94700e+03],
       [1.00000e+00, 8.85000e+01, 2.59426e+05, 2.32500e+03, 1.45600e+03,
        1.08632e+05, 1.94800e+03],
       [1.00000e+00, 8.82000e+01, 2.58054e+05, 3.68200e+03, 1.61600e+03,
        1.09773e+05, 1.94900e+03],
       [1.00000e+00, 8.95000e+01, 2.84599e+05, 3.35100e+03, 1.65000e+03,
        1.10929e+05, 1.95000e+03],
       [1.00000e+00, 9.62000e+01, 3.28975e+05, 2.09900e+03, 3.09900e+03,
        1.12075e+05, 1.95100e+03],
       [1.00000e+00, 9.81000e+01, 3.46999e+05, 1.93200e+03, 3.59400e+03,
        1.13270e+05, 1.95200e+03],
       [1.00000e+00, 9.90000e+01, 3.65385e+05, 1.87000e+03, 3.54700e+03,
        1.15094e+05, 1.95300e+03],
       [1.00000e+00, 1.00000e+02, 3.63112e+05, 3.57800e+03, 3.35000e+03,
        1.16219e+05, 1.95400e+03],
       [1.00000e+00, 1.01200e+02, 3.97469e+05, 2.90400e+03, 3.04800e+03,
        1.17388e+05, 1.95500e+03],
       [1.00000e+00, 1.04600

In [33]:
ols_resid = sm.OLS(data.endog, data.exog).fit().resid

In [34]:
ols_resid

array([ 267.34002977,  -94.01394239,   46.28716776, -410.11462192,
        309.71459077, -249.31121532, -164.04895639,  -13.18035686,
         14.30477261,  455.39409456,  -17.26892711,  -39.05504251,
       -155.54997358,  -85.67130803,  341.93151397, -206.75782518])

In [35]:
resid_fit = sm.OLS(ols_resid[1:], sm.add_constant(ols_resid[:-1])).fit()

In [36]:
print(resid_fit.tvalues[1])
print(resid_fit.pvalues[1])

-1.4390229839613828
0.17378444789154032


In [37]:
rho = resid_fit.params[1]
print(rho)

-0.3634294908742479


In [38]:
from scipy.linalg import toeplitz
toeplitz(range(5))

array([[0, 1, 2, 3, 4],
       [1, 0, 1, 2, 3],
       [2, 1, 0, 1, 2],
       [3, 2, 1, 0, 1],
       [4, 3, 2, 1, 0]])

In [39]:
order = toeplitz(range(len(ols_resid)))

In [40]:
print(order)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [ 2  1  0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [ 3  2  1  0  1  2  3  4  5  6  7  8  9 10 11 12]
 [ 4  3  2  1  0  1  2  3  4  5  6  7  8  9 10 11]
 [ 5  4  3  2  1  0  1  2  3  4  5  6  7  8  9 10]
 [ 6  5  4  3  2  1  0  1  2  3  4  5  6  7  8  9]
 [ 7  6  5  4  3  2  1  0  1  2  3  4  5  6  7  8]
 [ 8  7  6  5  4  3  2  1  0  1  2  3  4  5  6  7]
 [ 9  8  7  6  5  4  3  2  1  0  1  2  3  4  5  6]
 [10  9  8  7  6  5  4  3  2  1  0  1  2  3  4  5]
 [11 10  9  8  7  6  5  4  3  2  1  0  1  2  3  4]
 [12 11 10  9  8  7  6  5  4  3  2  1  0  1  2  3]
 [13 12 11 10  9  8  7  6  5  4  3  2  1  0  1  2]
 [14 13 12 11 10  9  8  7  6  5  4  3  2  1  0  1]
 [15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]]


In [41]:
sigma = rho**order
gls_model = sm.GLS(data.endog, data.exog, sigma=sigma)

In [42]:
gls_results = gls_model.fit()

In [44]:
gls_results.summary()

/home/aditya/miniconda3/envs/tfenv/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:430: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=16 observations were given.
  return hypotest_fun_in(*args, **kwds)


<class 'statsmodels.iolib.summary.Summary'>
"""
                            GLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.998
Model:                            GLS   Adj. R-squared:                  0.997
Method:                 Least Squares   F-statistic:                     724.0
Date:                Thu, 12 Mar 2026   Prob (F-statistic):           1.48e-11
Time:                        18:50:23   Log-Likelihood:                -107.50
No. Observations:                  16   AIC:                             229.0
Df Residuals:                       9   BIC:                             234.4
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.798e+06   6.71e+05     -5.663      0.000   -5.32e+06   -2.28e+06
x1           -12.7656     69.431     -0.184      0.858    -169.829     144.298
x2            -0.0380      0.026     -1.448      0.182      -0.097       0.021
x3            -2.1869      0.382     -5.719      0.000      -3.052      -1.322
x4            -1.1518      0.165     -6.970      0.000      -1.526      -0.778
x5            -0.0681      0.176     -0.386      0.709      -0.467       0.331
x6          1993.9529    342.635      5.819      0.000    1218.860    2769.046
==============================================================================
Omnibus:                        0.117   Durbin-Watson:                   2.611
Prob(Omnibus):                  0.943   Jarque-Bera (JB):                0.340
Skew:                          -0.036   Prob(JB):                        0.844
Kurtosis:                       2.290   Cond. No.                     5.61e+09
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.61e+09. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [45]:
glsar_model = sm.GLSAR(data.endog, data.exog, 1)
glsar_results = glsar_model.iterative_fit(1)
glsar_results.summary()

/home/aditya/miniconda3/envs/tfenv/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:430: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=15 observations were given.
  return hypotest_fun_in(*args, **kwds)


<class 'statsmodels.iolib.summary.Summary'>
"""
                           GLSAR Regression Results                           
==============================================================================
Dep. Variable:                      y   R-squared:                       0.996
Model:                          GLSAR   Adj. R-squared:                  0.992
Method:                 Least Squares   F-statistic:                     295.2
Date:                Thu, 12 Mar 2026   Prob (F-statistic):           6.09e-09
Time:                        18:52:16   Log-Likelihood:                -102.04
No. Observations:                  15   AIC:                             218.1
Df Residuals:                       8   BIC:                             223.0
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.468e+06   8.72e+05     -3.979      0.004   -5.48e+06   -1.46e+06
x1            34.5568     84.734      0.408      0.694    -160.840     229.953
x2            -0.0343      0.033     -1.047      0.326      -0.110       0.041
x3            -1.9621      0.481     -4.083      0.004      -3.070      -0.854
x4            -1.0020      0.211     -4.740      0.001      -1.489      -0.515
x5            -0.0978      0.225     -0.435      0.675      -0.616       0.421
x6          1823.1829    445.829      4.089      0.003     795.100    2851.266
==============================================================================
Omnibus:                        1.960   Durbin-Watson:                   2.554
Prob(Omnibus):                  0.375   Jarque-Bera (JB):                1.423
Skew:                           0.713   Prob(JB):                        0.491
Kurtosis:                       2.508   Cond. No.                     4.80e+09
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.8e+09. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [48]:
print(gls_results.params)
print(glsar_results.params)
print("=====================================")
print(gls_results.bse)
print(glsar_results.bse)

[-3.79785490e+06 -1.27656454e+01 -3.80013250e-02 -2.18694871e+00
 -1.15177649e+00 -6.80535580e-02  1.99395293e+03]
[-3.46796063e+06  3.45567846e+01 -3.43410090e-02 -1.96214395e+00
 -1.00197296e+00 -9.78045986e-02  1.82318289e+03]
[6.70688699e+05 6.94308073e+01 2.62476822e-02 3.82393151e-01
 1.65252692e-01 1.76428334e-01 3.42634628e+02]
[8.71584052e+05 8.47337145e+01 3.28032450e-02 4.80544865e-01
 2.11383871e-01 2.24774369e-01 4.45828748e+02]
